spring:
  application:
    name: ${artifactId}
  profiles:
    active: local
  dubbo:
    application:
      name: ${artifactId}
    protocol:
      name: dubbo
      port: 20880
    consumer:
      check: false
    registry:
      check: false
swagger:
  base-package: ${basePackage}.controller
  info:
    title: ${artifactId}
server:
  port: 8080
logging:
  file: <%='logs/${spring.application.name}.log'%>
